### ISSUE TITLE
line #65 to #68

### ISSUE THREAD

**Issue by rabia-aaziz** [Bazelah/test-may09#4]
aap ol mai text nahi likh sakhtay ol mai li k tag mai text likh sakhtay hain
https://github.com/Bazelah/test-may09/blob/d6e5c4e106e5ff5b5dc17ffd0f1351bb93d85766/index.html#L65

https://github.com/Bazelah/test-may09/blob/d6e5c4e106e5ff5b5dc17ffd0f1351bb93d85766/index.html#L66

https://github.com/Bazelah/test-may09/blob/d6e5c4e106e5ff5b5dc17ffd0f1351bb93d85766/index.html#L67

https://github.com/Bazelah/test-may09/blob/d6e5c4e106e5ff5b5dc17ffd0f1351bb93d85766/index.html#L68

**Comment by Bazelah** [comment]
resolved

**Comment by rabia-aaziz** [comment]
https://github.com/Bazelah/test-may09/blob/d6e5c4e106e5ff5b5dc17ffd0f1351bb93d85766/index.html#L65

you still didn't solve

**Comment by Bazelah** [comment]
#4 done
